### ISSUE TITLE
curious about your work with Khoral's viff-xv

### ISSUE THREAD

**Issue by ebo** [patrick-c-odriscoll/viff-xv#1]
I tried to find your contact info, but failed so I thought I would write directly.  I worked extensively with Khoros throughout the 90's (and even have a commercial license for 2.3).

I am curious what motivated you to write an I/O library for viff.

BTW, I was tracking down what happened to VisiQuest (which was Accusoft's rebranding of Khoros) when I stumbled upon your work...

  EBo --

**Comment by patrick-c-odriscoll** [comment]
I just sent you a message on linked in. 

Long story short, I wanted to make it easier for any other poor researcher who needs to read the data format.
